# -*- coding: utf-8 -*-
"""Reliance Industries Stock Price Forecasting Using VAR Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiU7KpUlevHJ3MJRYjl3FMPBUBHuTgag

Install Required Libraries
"""

!pip install statsmodels yfinance --quiet

"""Import Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

from sklearn.metrics import mean_squared_error

import warnings
warnings.filterwarnings('ignore')

"""Load the Dataset"""

df = pd.read_csv('RELIANCE.NS_1973-05-08_2025-03-01.csv')

df.head()

"""Check Dataset Information"""

df.shape
df.info()
df.isnull().sum()

"""Convert Date Column"""

df['date'] = pd.to_datetime(df['date'])

"""Set Date as Index"""

df.set_index('date', inplace=True)

df.head()

print(df.columns)

"""Select Variables for VAR"""

data = df[
[
    'open',
    'high',
    'low',
    'close',
    'volume'
]
]

data.head()

"""Check Missing Values"""

data.isnull().sum()

"""Remove Missing Values"""

data = data.dropna()

print(data.shape)

"""Plot Variables"""

data.plot(
    figsize=(15,8),
    subplots=True
)

plt.show()

"""ADF Test Function"""

from statsmodels.tsa.stattools import adfuller

def adf_test(series):

    result = adfuller(series)

    print("ADF Statistic :", result[0])
    print("p-value :", result[1])

    if result[1] < 0.05:
        print("Stationary")
    else:
        print("Non-Stationary")

for col in data.columns:

    print("\nColumn:", col)

    adf_test(data[col])

"""| Variable | ADF Statistic | p-value | Result           |
| -------- | ------------- | ------- | ---------------- |
| Open     | 0.3435        | 0.9793  | ❌ Non-Stationary |
| High     | 0.3788        | 0.9807  | ❌ Non-Stationary |
| Low      | 0.3036        | 0.9775  | ❌ Non-Stationary |
| Close    | 0.3706        | 0.9804  | ❌ Non-Stationary |
| Volume   | -7.0389       | 0.0000  | ✅ Stationary     |
=========

VAR requires all variables to be stationary.

Since Open, High, Low, and Close are non-stationary, we must transform the data before fitting the VAR model.

First Differencing
"""

# First Differencing
df_diff = df[['open','high','low','close','volume']].diff().dropna()

# Check again
from statsmodels.tsa.stattools import adfuller

for col in df_diff.columns:
    result = adfuller(df_diff[col])
    print(f"\nColumn: {col}")
    print("ADF Statistic:", result[0])
    print("p-value:", result[1])

"""ADF Test After First Differencing

| Variable | ADF Statistic | p-value  | Result       |
| -------- | ------------- | -------- | ------------ |
| Open     | -36.18        | 0.0000   | ✅ Stationary |
| High     | -32.70        | 0.0000   | ✅ Stationary |
| Low      | -22.48        | 0.0000   | ✅ Stationary |
| Close    | -14.58        | 4.48e-27 | ✅ Stationary |
| Volume   | -20.85        | 0.0000   | ✅ Stationary |
=========

Analysis

All variables now have:

p-value < 0.05
Strongly negative ADF statistics

Lag Order Selection
"""

from statsmodels.tsa.api import VAR

model = VAR(df_diff)

lag_results = model.select_order(maxlags=15)

print(lag_results.summary())

"""| Criterion | Best Lag |
| --------- | -------- |
| AIC       | **15** ✅ |
| FPE       | **15** ✅ |
| HQIC      | **15** ✅ |
| BIC       | **10** ✅ |

VAR needs a lag value (previous days' influence).

Example:

VAR(1) → Uses previous 1 day
VAR(2) → Uses previous 2 days
VAR(5) → Uses previous 5 days

The optimal lag is selected using:
=======

| Criterion | Meaning                            |
| --------- | ---------------------------------- |
| AIC       | Akaike Information Criterion       |
| BIC       | Bayesian Information Criterion     |
| HQIC      | Hannan-Quinn Information Criterion |
| FPE       | Final Prediction Error             |

======

Train VAR Model
"""

from statsmodels.tsa.api import VAR

model = VAR(df_diff)

var_model = model.fit(15)

print(var_model.summary())

"""Residual Correlation Matrix Analysis


"""

forecast_steps = 7

forecast = var_model.forecast(
    y=df_diff.values[-15:],
    steps=forecast_steps
)

forecast_df = pd.DataFrame(
    forecast,
    columns=df_diff.columns
)

forecast_df

last_actual = df[['open','high','low','close','volume']].iloc[-1]

forecast_actual = forecast_df.cumsum()

for col in forecast_actual.columns:
    forecast_actual[col] += last_actual[col]

forecast_actual

"""VAR Model Forecasting is successfully completed

7-Day Reliance Industries Stock Forecast

| Day   |    Open |    High |     Low |   Close |
| ----- | ------: | ------: | ------: | ------: |
| Day 1 | 1198.18 | 1208.12 | 1188.36 | 1199.46 |
| Day 2 | 1200.06 | 1209.98 | 1189.94 | 1200.36 |
| Day 3 | 1199.46 | 1211.19 | 1189.54 | 1200.84 |
| Day 4 | 1200.03 | 1211.15 | 1189.84 | 1201.53 |
| Day 5 | 1199.69 | 1211.19 | 1191.35 | 1201.53 |
| Day 6 | 1200.64 | 1212.41 | 1193.38 | 1203.10 |
| Day 7 | 1202.66 | 1214.13 | 1195.99 | 1206.08 |

==========

**Forecast Analysis**

Close Price Trend

| Day   | Close Price |
| ----- | ----------: |
| Day 1 |     1199.46 |
| Day 7 |     1206.08 |


Expected Increase:

1206.08 - 1199.46 = 6.62

7-Day Forecast Close Price Trend based on VAR Model
"""

import matplotlib.pyplot as plt

days = ['Day1','Day2','Day3','Day4','Day5','Day6','Day7']
close_prices = [1199.46,1200.36,1200.84,1201.53,1201.53,1203.10,1206.08]

plt.figure(figsize=(10,5))
plt.plot(days, close_prices, marker='o', linewidth=2)

plt.title("Reliance Industries Stock Price Forecast using VAR Model")
plt.xlabel("Forecast Days")
plt.ylabel("Forecasted Close Price")
plt.grid(True)

for i, value in enumerate(close_prices):
    plt.text(i, value+0.2, round(value,2), ha='center')

plt.show()

"""Conclusion & Result Summary

**Reliance Industries Stock Price Forecasting Using VAR Model**


| Parameter                      | Result                                             |
| ------------------------------ | -------------------------------------------------- |
| Company                        | Reliance Industries Ltd.                           |
| Dataset Period                 | 2023 – 2025                                        |
| Variables Used                 | Open, High, Low, Close, Volume                     |
| Model Applied                  | VAR (Vector Autoregression)                        |
| Stationarity Test              | Augmented Dickey-Fuller (ADF)                      |
| Initial ADF Result             | Open, High, Low, Close were Non-Stationary         |
| Data Transformation            | First-Order Differencing                           |
| Final ADF Result               | All Variables Stationary                           |
| Optimal Lag Selected           | VAR(15)                                            |
| Lag Selection Criteria         | AIC, FPE, HQIC                                     |
| Forecast Horizon               | 7 Trading Days                                     |
| Forecasted Close Price (Day 1) | 1199.46                                            |
| Forecasted Close Price (Day 7) | 1206.08                                            |
| Expected Price Change          | +6.62 Points                                       |
| Predicted Trend                | Upward Trend                                       |
| Market Outlook                 | Positive / Bullish                                 |
| Residual Analysis              | Model Captured Variable Relationships Successfully |
| Forecast Reliability           | Suitable for Short-Term Forecasting                |


"""